### ISSUE TITLE
Class 'Lucasvdh\LaravelDkim\MailServiceProvider' not found

### ISSUE THREAD

**Issue by kodelio** [rapideinternet/laraveldkim#2]
Getting this error when installing the package and replacing the MailServiceProvider :
`Class 'Lucasvdh\LaravelDkim\MailServiceProvider' not found`

How can I solve it ?

**Comment by rapideinternet** [comment]
The was an error in the composer.json of the package.

Please run `composer update` and the issue should be resolved
